### ISSUE TITLE
Return plot of all streams in equatorial coordinates

### ISSUE THREAD

**Issue by abonaca** [cmateu/galstreams#27]
This has been my go to for planning observations, and it would be awesome to have that figure available again!

**Comment by cmateu** [comment]
Back by popular demand... I give you... the plot_stream_compilation method, for one-liner library plots in your favorite coordinate frame ;). You can now find the map in equatorial coordinates in the (new) Quick plots section (see screenshot below). More involved "by-hand" plot examples are at the end of the notebook in the "More plotting examples with Basemap section". 
![Screen Shot 2023-04-26 at 12 07 01 PM](https://user-images.githubusercontent.com/4968584/234619332-bf84c82e-3920-4b06-87a5-1f718fb3dabd.png)

**Comment by abonaca** [comment]
Thank you so, so much!
