### ISSUE TITLE
Astropy coordinate frames

### ISSUE THREAD

**Issue by adrn** [cmateu/galstreams#4]
Hey @cmateu 👋

Have you thought about the possibility of making [Astropy coordinate frames](http://docs.astropy.org/en/latest/coordinates/index.html) for the streams? We support most possible astronomical coordinate transformations (including velocity components / proper motions!), like galactic, ICRS, ecliptic, etc. For stream frames, I have a few examples in [gala](http://gala.adrian.pw/en/latest/coordinates/index.html) for Pal 5, GD-1, Sagittarius, Orphan.

Let me know if you'd like to chat!

**Comment by cmateu** [comment]
yes, I’d absolutely like to chat about that! 

I hadn’t thought about that specifically but
I was definitely hoping to get some pointers to make the library 
more general and less home-made :)

**Comment by adrn** [comment]
The first stab at this is implemented! Woohoo!
